spring:
  application:
    name: sensors-central-service

warehouse:
  nats:
    server:
      uri: nats://sensor-nats-server:4222
      user: sensor-subscriber
      password: changeme

  sensors:
    - id: t1
      subject: temperature
      udp-port: 3344
    - id: h1
      subject: humidity
      udp-port: 3355